### ISSUE TITLE
Problem with special character

### ISSUE THREAD

**Issue by adrienmartinau** [MELVARDEV/League-Pass-Manager#2]
hello, informations with ranking + icon dont show up with special character in this case its with "Òracle" Ò"

**Comment by MELVARDEV** [comment]
Should work now. Please let me know if it does.

**Comment by adrienmartinau** [comment]
it works now!!

**Comment by adrienmartinau** [comment]
and maybe can i ask you to make a way to order from highest elo to lowest

**Comment by MELVARDEV** [comment]
Thanks for letting me know. I'll keep your suggestion in mind when I'll be working on the app once I find some spare time.
